In [33]:
# Dependencies and Setup

import pandas as pd
import numpy as np

In [34]:
steam_final_cleaned = pd.read_csv('../Scraped Data/steam_final_cleaned.csv', encoding='utf-8-sig')
steam_final = steam_final_cleaned[['appid', 'metascore', 'recommendations', 'positive', 'negative', 'developer', 'publisher']]
steam_final

,appid,metascore,recommendations,positive,negative,developer,publisher
0,10,88.0,100006.0,169280.0,4360.0,Valve,Valve
1,20,0.0,3754.0,4628.0,800.0,Valve,Valve
2,30,79.0,2779.0,4527.0,493.0,Valve,Valve
3,40,0.0,1276.0,1651.0,353.0,Valve,Valve
4,50,0.0,8162.0,9938.0,520.0,Gearbox Software,Valve
...,...,...,...,...,...,...,...
33755,1499780,0.0,0.0,1.0,1.0,INFINITY BRIDGE,INFINITY BRIDGE
33756,1500260,0.0,0.0,0.0,1.0,"Cosmin, Josh",GamesLtd.
33757,1500490,0.0,0.0,2.0,0.0,"klutzGames, Fleischfilm","klutzGames, Fleischfilm"
33758,1502790,0.0,0.0,10.0,0.0,AGM Studios,AGM Studios
33759,1504150,0.0,0.0,21.0,2.0,"Eerie Guest, tinyBuild",tinyBuild

In [35]:
all_param_binary_tags = pd.read_csv('../reduced_data/all_param_binary_tags.csv')
all_param_binary_tags

,appid,maxccu,success_class,suc_class,followers,positive,negative,maxprice,maxdiscount,totaltags,...,tagphilisophical,taggaming,tagfaith,tagmysterydungeon,tagfeaturefilm,tagsteammachine,tagclicker,taghardware,tag360video,tagvronly
0,1272460,2,F,0,32,0,1,1899,60,127,...,0,0,0,0,0,0,0,0,0,0
1,380130,1,F,0,620,0,1,499,10,168,...,0,0,0,0,0,0,0,0,0,0
2,398950,2,F,0,246,0,1,499,10,40,...,0,0,0,0,0,0,0,0,0,0
3,381290,1,F,0,390,0,1,999,0,73,...,0,0,0,0,0,0,0,0,0,0
4,431470,1,F,0,55,0,1,699,90,111,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39619,440,147360,AAA,1,0,703615,44046,0,0,261208,...,0,0,0,0,0,0,0,0,0,0
39620,359550,199307,AAA,1,1162283,741118,99312,5999,75,77135,...,0,0,0,0,0,0,0,0,0,0
39621,578080,3257248,AAA,1,3450113,885668,757174,2999,50,98104,...,0,0,0,0,0,0,0,0,0,0
39622,570,1295107,AAA,1,0,1217813,224709,0,0,184987,...,0,0,0,0,0,0,0,0,0,0
39623,730,1308963,AAA,1,0,4598654,621427,1499,50,740953,...,0,0,0,0,0,0,0,0,0,0

In [36]:
steam_all_param_binary = pd.merge(steam_final, all_param_binary_tags, on="appid", how="right")
steam_all_param_binary

,appid,metascore,recommendations,positive_x,negative_x,developer,publisher,maxccu,success_class,suc_class,...,tagphilisophical,taggaming,tagfaith,tagmysterydungeon,tagfeaturefilm,tagsteammachine,tagclicker,taghardware,tag360video,tagvronly
0,10,88.0,100006.0,169280.0,4360.0,Valve,Valve,31930,A,1,...,0,0,0,0,0,0,0,0,0,0
1,20,0.0,3754.0,4628.0,800.0,Valve,Valve,236,F,0,...,0,0,0,0,0,0,0,0,0,0
2,30,79.0,2779.0,4527.0,493.0,Valve,Valve,364,F,0,...,0,0,0,0,0,0,0,0,0,0
3,40,0.0,1276.0,1651.0,353.0,Valve,Valve,629,F,0,...,0,0,0,0,0,0,0,0,0,0
4,50,0.0,8162.0,9938.0,520.0,Gearbox Software,Valve,620,F,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39619,875210,NaN,NaN,NaN,NaN,NaN,NaN,25160,A,1,...,0,0,0,0,0,0,0,0,0,0
39620,435400,NaN,NaN,NaN,NaN,NaN,NaN,763,F,0,...,0,0,0,0,0,0,0,0,0,0
39621,1127400,NaN,NaN,NaN,NaN,NaN,NaN,2691,D,0,...,0,0,0,0,0,0,0,0,0,0
39622,115300,NaN,NaN,NaN,NaN,NaN,NaN,5,F,0,...,0,0,0,0,0,0,0,0,0,0
39623,900883,NaN,NaN,NaN,NaN,NaN,NaN,0,F,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
steam_all_param_binary.to_csv('../reduced_data/steam_all_param_binary_tags_merged.csv', encoding='utf-8-sig', index = False)

In [38]:
all_param = pd.read_csv('../reduced_data/all_param.csv')
all_param

,appid,maxccu,success_class,suc_class,followers,positive,negative,maxprice,maxdiscount,totaltags,...,tagphilisophical,taggaming,tagfaith,tagmysterydungeon,tagfeaturefilm,tagsteammachine,tagclicker,taghardware,tag360video,tagvronly
0,1272460,2,F,0,32,0,1,1899,60,127,...,0,0,0,0,0,0,0,0,0,0
1,380130,1,F,0,620,0,1,499,10,168,...,0,0,0,0,0,0,0,0,0,0
2,398950,2,F,0,246,0,1,499,10,40,...,0,0,0,0,0,0,0,0,0,0
3,381290,1,F,0,390,0,1,999,0,73,...,0,0,0,0,0,0,0,0,0,0
4,431470,1,F,0,55,0,1,699,90,111,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39619,440,147360,AAA,1,0,703615,44046,0,0,261208,...,0,0,0,0,0,0,0,0,0,0
39620,359550,199307,AAA,1,1162283,741118,99312,5999,75,77135,...,0,0,0,0,0,0,0,0,0,0
39621,578080,3257248,AAA,1,3450113,885668,757174,2999,50,98104,...,0,0,0,0,0,0,0,0,0,0
39622,570,1295107,AAA,1,0,1217813,224709,0,0,184987,...,0,0,0,0,0,0,0,0,0,0
39623,730,1308963,AAA,1,0,4598654,621427,1499,50,740953,...,0,0,0,0,0,0,0,0,0,0

In [39]:
steam_all_param = pd.merge(steam_final, all_param, on="appid", how="right")
steam_all_param

,appid,metascore,recommendations,positive_x,negative_x,developer,publisher,maxccu,success_class,suc_class,...,tagphilisophical,taggaming,tagfaith,tagmysterydungeon,tagfeaturefilm,tagsteammachine,tagclicker,taghardware,tag360video,tagvronly
0,10,88.0,100006.0,169280.0,4360.0,Valve,Valve,31930,A,1,...,0,0,0,0,0,0,0,0,0,0
1,20,0.0,3754.0,4628.0,800.0,Valve,Valve,236,F,0,...,0,0,0,0,0,0,0,0,0,0
2,30,79.0,2779.0,4527.0,493.0,Valve,Valve,364,F,0,...,0,0,0,0,0,0,0,0,0,0
3,40,0.0,1276.0,1651.0,353.0,Valve,Valve,629,F,0,...,0,0,0,0,0,0,0,0,0,0
4,50,0.0,8162.0,9938.0,520.0,Gearbox Software,Valve,620,F,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39619,875210,NaN,NaN,NaN,NaN,NaN,NaN,25160,A,1,...,0,0,0,0,0,0,0,0,0,0
39620,435400,NaN,NaN,NaN,NaN,NaN,NaN,763,F,0,...,0,0,0,0,0,0,0,0,0,0
39621,1127400,NaN,NaN,NaN,NaN,NaN,NaN,2691,D,0,...,0,0,0,0,0,0,0,0,0,0
39622,115300,NaN,NaN,NaN,NaN,NaN,NaN,5,F,0,...,0,0,0,0,0,0,0,0,0,0
39623,900883,NaN,NaN,NaN,NaN,NaN,NaN,0,F,0,...,0,0,0,0,0,0,0,0,0,0

In [40]:
steam_all_param.to_csv('../reduced_data/steam_all_param_merged.csv', encoding='utf-8-sig', index = False)