In [ ]:
# slightly worse :/

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
all_param_df = pd.read_csv("..\\reduced_data\\steam_all_param_merged_nan_removed.csv")
all_param_df.shape

(31686, 357)

In [3]:
y = all_param_df['maxprice']

In [4]:
y

0        999
1        499
2        499
3        499
4        499
        ...
31681     99
31682     99
31683    999
31684      0
31685      0
Name: maxprice, Length: 31686, dtype: int64

In [5]:
X = all_param_df.drop(['appid','maxccu','success_class','suc_class','followers','positive_y', 'negative_y', 'totaltags', 'recommendations', 'positive_x', 'negative_x', 'maxprice']  , axis=1)

In [6]:
X.shape

(31686, 345)

In [7]:
X['developer']= X['developer'].astype('category')

In [8]:
X['developer']= X['developer'].cat.codes
X.head()

,metascore,developer,publisher,maxdiscount,tagstrategy,tagaction,tagadventure,tagdesignillustration,tagutilities,tagfreetoplay,...,tagphilisophical,taggaming,tagfaith,tagmysterydungeon,tagfeaturefilm,tagsteammachine,tagclicker,taghardware,tag360video,tagvronly
0,88,18255,Valve,90,602,5337,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,18255,Valve,90,0,738,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,79,18255,Valve,90,14,156,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,18255,Valve,90,0,626,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,6704,Valve,90,0,312,109,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
X['publisher'] = X['publisher'].astype('category')

In [10]:
X['publisher']= X['publisher'].cat.codes
X.head()

,metascore,developer,publisher,maxdiscount,tagstrategy,tagaction,tagadventure,tagdesignillustration,tagutilities,tagfreetoplay,...,tagphilisophical,taggaming,tagfaith,tagmysterydungeon,tagfeaturefilm,tagsteammachine,tagclicker,taghardware,tag360video,tagvronly
0,88,18255,15348,90,602,5337,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,18255,15348,90,0,738,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,79,18255,15348,90,14,156,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,18255,15348,90,0,626,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,6704,15348,90,0,312,109,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
print(X)

       metascore  developer  publisher  maxdiscount  tagstrategy  tagaction  \
0             88      18255      15348           90          602       5337
1              0      18255      15348           90            0        738
2             79      18255      15348           90           14        156
3              0      18255      15348           90            0        626
4              0       6704      15348           90            0        312
...          ...        ...        ...          ...          ...        ...
31681          0       7882       6697           40            0          0
31682          0       3589       5609            0           20         72
31683          0      19968      16855            0            0        214
31684          0        349        353            0            0          0
31685          0       5173      17127            0          192          0

       tagadventure  tagdesignillustration  tagutilities  tagfreetoplay  ...  \
0                 0                      0             0              0  ...
1                 0                      0             0              0  ...
2                 0                      0             0              0  ...
3                 0                      0             0              0  ...
4               109                      0             0              0  ...
...             ...                    ...           ...            ...  ...
31681             0                      0             0              0  ...
31682            65                      0             0              0  ...
31683             0                      0             0              0  ...
31684           476                      0             0              0  ...
31685           200                      0             0              0  ...

       tagphilisophical  taggaming  tagfaith  tagmysterydungeon  \
0                     0          0         0                  0
1                     0          0         0                  0
2                     0          0         0                  0
3                     0          0         0                  0
4                     0          0         0                  0
...                 ...        ...       ...                ...
31681                 0          0         0                  0
31682                 0          0         0                  0
31683                 0          0         0                  0
31684                 0          0         0                  0
31685                 0          0         0                  0

       tagfeaturefilm  tagsteammachine  tagclicker  taghardware  tag360video  \
0                   0                0           0            0            0
1                   0                0           0            0            0
2                   0                0           0            0            0
3                   0                0           0            0            0
4                   0                0           0            0            0
...               ...              ...         ...          ...          ...
31681               0                0         183            0            0
31682               0                0           0            0            0
31683               0                0           0            0            0
31684               0                0           0            0            0
31685               0                0           0            0            0

       tagvronly
0              0
1              0
2              0
3              0
4              0
...          ...
31681          0
31682          0
31683          0
31684          0
31685          0

[31686 rows x 345 columns]

In [12]:
y= y.values.reshape(-1,1)

In [13]:
print(y)

[[999]
 [499]
 [499]
 ...
 [999]
 [  0]
 [  0]]

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

X_train.head()

,metascore,developer,publisher,maxdiscount,tagstrategy,tagaction,tagadventure,tagdesignillustration,tagutilities,tagfreetoplay,...,tagphilisophical,taggaming,tagfaith,tagmysterydungeon,tagfeaturefilm,tagsteammachine,tagclicker,taghardware,tag360video,tagvronly
19192,0,6588,5544,0,0,0,30,0,0,35,...,0,0,0,0,0,0,0,0,0,0
2374,68,33,71,80,0,111,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27982,0,18808,10245,0,0,55,0,0,0,59,...,0,0,0,0,0,0,0,0,0,0
22188,0,15670,13222,0,0,0,0,0,0,21,...,0,0,0,0,0,0,0,0,0,0
14845,0,2749,2370,40,57,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)

In [16]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [17]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train_scaled, y_train_scaled)

LinearRegression()

In [18]:
score = regressor.score(X_train_scaled, y_train_scaled)
print(score)

0.0360525818770161

In [19]:
from sklearn.metrics import mean_squared_error

predictions = regressor.predict(X_train_scaled)
MSE = mean_squared_error(y_train_scaled, predictions)
r2 = regressor.score(X_train_scaled, y_train_scaled)

print(f"MSE: {MSE}, R2: {r2}")

MSE: 0.9639474181229838, R2: 0.0360525818770161